### ISSUE TITLE
opentelekomcloud.cloud.subnet  fails when changing description parameter 

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/ansible-collection-cloud#178]
Hi all,
today i tried:

- opentelekomcloud.cloud.subnet

When i run the the following playbook the first time with description parameter everything is working fine.
```
- name: "Fetch id {{ vpcid.stdout }} for vpc  name {{snnet.sn_vpc_name}}"
  set_fact:
    sn_vpc_id={{ vpcid.stdout }}

- name: "Create subnet {{snnet.sn_name}}"
  opentelekomcloud.cloud.subnet:
    name: "{{snnet.sn_name}}"
    vpc_id: "{{ sn_vpc_id}}"
    cidr: "{{ snnet.sn_cidr }}"
    gateway_ip: "{{ snnet.sn_gateway_ip }}"
    #description: "{{snnet.sn_description}}"
    description: "{{ snnet.sn_description }}"
    dns_list:
      - "{{dns_1}}"
      - "{{dns_2}}"
```
If i change the description and rerun the playbook it fails with the following error:

```

The full traceback is:
Traceback (most recent call last):
  File "/home/linux/.ansible/tmp/ansible-tmp-1645541884.0863757-233713335327632/AnsiballZ_subnet.py", line 102, in <module>
    _ansiballz_main()
  File "/home/linux/.ansible/tmp/ansible-tmp-1645541884.0863757-233713335327632/AnsiballZ_subnet.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/linux/.ansible/tmp/ansible-tmp-1645541884.0863757-233713335327632/AnsiballZ_subnet.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.opentelekomcloud.cloud.plugins.modules.subnet', init_globals=None, run_name='__main__', alter_sys=False)
  File "/usr/lib64/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_opentelekomcloud.cloud.subnet_payload_jldr6mt3/ansible_opentelekomcloud.cloud.subnet_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/subnet.py", line 349, in <module>
  File "/tmp/ansible_opentelekomcloud.cloud.subnet_payload_jldr6mt3/ansible_opentelekomcloud.cloud.subnet_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/subnet.py", line 345, in main
  File "/tmp/ansible_opentelekomcloud.cloud.subnet_payload_jldr6mt3/ansible_opentelekomcloud.cloud.subnet_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/module_utils/otc.py", line 201, in __call__
  File "/tmp/ansible_opentelekomcloud.cloud.subnet_payload_jldr6mt3/ansible_opentelekomcloud.cloud.subnet_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/subnet.py", line 263, in run
TypeError: fail_json() takes 1 positional argument but 2 were given

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/linux/.ansible/tmp/ansible-tmp-1645541884.0863757-233713335327632/AnsiballZ_subnet.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/linux/.ansible/tmp/ansible-tmp-1645541884.0863757-233713335327632/AnsiballZ_subnet.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/linux/.ansible/tmp/ansible-tmp-1645541884.0863757-233713335327632/AnsiballZ_subnet.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.opentelekomcloud.cloud.plugins.modules.subnet', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/usr/lib64/python3.6/runpy.py\", line 208, in run_module\n    return _run_code(code, {}, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_opentelekomcloud.cloud.subnet_payload_jldr6mt3/ansible_opentelekomcloud.cloud.subnet_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/subnet.py\", line 349, in <module>\n  File \"/tmp/ansible_opentelekomcloud.cloud.subnet_payload_jldr6mt3/ansible_opentelekomcloud.cloud.subnet_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/subnet.py\", line 345, in main\n  File \"/tmp/ansible_opentelekomcloud.cloud.subnet_payload_jldr6mt3/ansible_opentelekomcloud.cloud.subnet_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/module_utils/otc.py\", line 201, in __call__\n  File \"/tmp/ansible_opentelekomcloud.cloud.subnet_payload_jldr6mt3/ansible_opentelekomcloud.cloud.subnet_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/subnet.py\", line 263, in run\nTypeError: fail_json() takes 1 positional argument but 2 were given\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Could you please check ?

Thanks in advance

Uli

**Comment by hadoopch** [comment]
Good morning everybody,

this issues is not fixed with latest release 0.12.

Best regards
Uli

**Comment by enrrou** [comment]
Checking it now

**Comment by enrrou** [comment]
@hadoopch 
fixed in 0.12.1.
try on your environment and let us know, please.
thanks

**Comment by hadoopch** [comment]
Hi Enrou,

i made an update to 0.12.1. But the error  still occurs when i change the description of a subnet and rerun the playbook afterwards

**Comment by enrrou** [comment]
It would be very helpful if you could send the full log of a task, including the parameters.

**Comment by gtema** [comment]
@hadoopch , sorry for long time for processing this
https://docs.otc.t-systems.com/virtual-private-cloud/api-ref/native_openstack_neutron_apis_v2.0/subnet/updating_a_subnet.html#vpc-subnet02-0004 describes that gateway_ip can not be updated. Sorry, but we can't help here.
